// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"toDoBackEnd/application"
	"toDoBackEnd/di/container"
	"toDoBackEnd/infra/persistence"
	"toDoBackEnd/presentation/grpc"
	"toDoBackEnd/proto/proto-gen/pb"
)

// Injectors from wire.go:

func NewUserServer() pb.UserServiceServer {
	client := container.FirestoreClient()
	logger := container.Logger()
	repository := persistence.NewUserRepository(client, logger)
	userService := application.NewUserService(repository, logger)
	userServiceServer := grpc.NewUserServer(userService, logger)
	return userServiceServer
}

// wire.go:

var wireSet = wire.NewSet(container.WireSet, grpc.WireSet, application.WireSet, persistence.WireSet)
